<a href="https://colab.research.google.com/github/Aaish48/ML/blob/main/ML_LAB_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Create a list
data_list = [10, 20, 30, 40, 50]

# Convert list to NumPy array
arr = np.array(data_list)

# Display array, shape, and data type
print("Array:", arr)
print("Shape:", arr.shape)
print("Data Type:", arr.dtype)

Array: [10 20 30 40 50]
Shape: (5,)
Data Type: int64


In [2]:
import numpy as np

# Create 3x4 matrix of zeros
zeros_matrix = np.zeros((3, 4))

# Create 2x5 matrix of ones
ones_matrix = np.ones((2, 5))

print("Zeros Matrix:\n", zeros_matrix)
print("Shape of Zeros Matrix:", zeros_matrix.shape)

print("\nOnes Matrix:\n", ones_matrix)
print("Shape of Ones Matrix:", ones_matrix.shape)

Zeros Matrix:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Shape of Zeros Matrix: (3, 4)

Ones Matrix:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Shape of Ones Matrix: (2, 5)


In [3]:
import numpy as np

# Create array from 1 to 12
arr = np.arange(1, 13)

# Reshape into 3x4 matrix
reshaped_arr = arr.reshape(3, 4)

print("Original Array:", arr)
print("Original Shape:", arr.shape)

print("\nReshaped Matrix:\n", reshaped_arr)
print("Reshaped Shape:", reshaped_arr.shape)

Original Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Original Shape: (12,)

Reshaped Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reshaped Shape: (3, 4)


In [4]:
import numpy as np

# Generate 10 random integers between 1 and 100
random_arr = np.random.randint(1, 100, 10)

print("Random Array:", random_arr)
print("Minimum:", random_arr.min())
print("Maximum:", random_arr.max())
print("Mean:", random_arr.mean())
print("Sum:", random_arr.sum())

Random Array: [21 28 92 96 24 36 64 46 57 80]
Minimum: 21
Maximum: 96
Mean: 54.4
Sum: 544


In [5]:
import pandas as pd

# Create a dictionary
data = {
    'Student': ['Amit', 'Priya', 'Rahul', 'Sneha', 'Vikram'],
    'Marks': [85, 92, 78, 88, 76]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display DataFrame and Data Types
print(df)
print("\nData Types:\n", df.dtypes)

  Student  Marks
0    Amit     85
1   Priya     92
2   Rahul     78
3   Sneha     88
4  Vikram     76

Data Types:
 Student    object
Marks       int64
dtype: object


In [6]:
import pandas as pd

# Create a dummy CSV file for demonstration
data = {
    'ID': range(1, 16),
    'Name': ['Student' + str(i) for i in range(1, 16)],
    'Score': [70, 80, 90, 65, 75, 85, 95, 60, 72, 82, 92, 68, 78, 88, 98]
}
pd.DataFrame(data).to_csv('students.csv', index=False)

# Read the CSV file
df = pd.read_csv('students.csv')

print("First 5 rows:")
print(df.head())

print("\nLast 5 rows:")
print(df.tail())

First 5 rows:
   ID      Name  Score
0   1  Student1     70
1   2  Student2     80
2   3  Student3     90
3   4  Student4     65
4   5  Student5     75

Last 5 rows:
    ID       Name  Score
10  11  Student11     92
11  12  Student12     68
12  13  Student13     78
13  14  Student14     88
14  15  Student15     98


In [7]:
import pandas as pd

# Load dataset
df = pd.read_csv('students.csv')

# Display dataset info
print("Dataset Structure:")
df.info()

Dataset Structure:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   ID      15 non-null     int64 
 1   Name    15 non-null     object
 2   Score   15 non-null     int64 
dtypes: int64(2), object(1)
memory usage: 492.0+ bytes


In [8]:
import pandas as pd

# Load dataset
df = pd.read_csv('students.csv')

# Display statistical summary
print("Statistical Summary:")
print(df.describe())

Statistical Summary:
              ID      Score
count  15.000000  15.000000
mean    8.000000  79.866667
std     4.472136  11.488296
min     1.000000  60.000000
25%     4.500000  71.000000
50%     8.000000  80.000000
75%    11.500000  89.000000
max    15.000000  98.000000
